package com.dj.mapper;

import com.dj.model.DataDo;

import java.util.List;

/**
 * 数据操作类
 *
 * @author 莫小阳
 */
public interface DataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    DataDo selectByKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    int insert(DataDo record);

    /**
     * 获取全数据
     *
     * @return 结果
     */
    List<DataDo> getAllData();


}