package com.dj.mapper;

import com.dj.model.ManagerInfoAll;
import com.dj.model.ManagerInfoDo;

import java.util.List;

public interface ManagerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated
     */
    int insert(ManagerInfoDo record);

    List<ManagerInfoAll> queryAll();
}