package com.dj.mapper;

import com.dj.model.ManagerJobDo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ManagerJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerjob
     *
     * @mbg.generated
     */
    ManagerJobDo selectByKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerjob
     *
     * @mbg.generated
     */
    int insert(ManagerJobDo record);

    void insertList(@Param("list") List<ManagerJobDo> list);
}