package com.dj.mapper;

import com.dj.model.ManagerDo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated
     */
    int insert(ManagerDo record);


    void insertList(List<ManagerDo> allManagerDo);

    /**
     * 查询所有
     *
     * @return 结果
     */
    List<ManagerDo> selectAll(@Param("begin") int begin, @Param("end") int end);

    List<ManagerDo> selectAllByT();
}