package com.dj.mapper;

import com.dj.model.ManagerInfoDo;

public interface ManagerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managerinfo
     *
     * @mbg.generated
     */
    int insert(ManagerInfoDo record);
}